/**
 * Catálogo oficial dos princípios, técnicas e Gambi Design Patterns do livro
 * "Programação Orientada a Gambiarra" — https://livropog.com.br
 *
 * Pontuação:
 *   princípio  → 1 ponto  (17 itens → máx 17 pts)
 *   técnica    → 2 pontos  (5 itens  → máx 10 pts)
 *   gdp        → 3 pontos  (20 itens → máx 60 pts)
 *                                      máx total: 87 pts (teórico)
 *
 * Na prática um único projeto raramente passa de 50 pts.
 */

export const PRINCIPIOS = [
    {
        id: 'enjambracao-criativistica',
        tipo: 'principio',
        nome: 'Enjambração Criativística',
        descricao: 'Use o código do sistema financeiro para criar o sistema de EAD.',
        sinais: [
            'código de um domínio sendo reutilizado em contexto completamente diferente',
            'classes ou módulos importados de subsistemas sem relação lógica',
            'nomes de variáveis que fazem referência a outro produto ou domínio',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'reflexao-reprodutoria',
        tipo: 'principio',
        nome: 'Reflexão Reprodutória',
        descricao: "Copiou o código da biblioteca XYZ. Ninguém vai notar.",
        sinais: [
            'blocos de código copiados de Stack Overflow, gists ou outras bibliotecas sem atribuição',
            'comentários em idioma diferente do restante do código',
            'estilos de código inconsistentes no mesmo arquivo — indentação, naming diferentes por trecho',
            'funções inteiras que existem em bibliotecas populares reimplementadas manualmente',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'reducao-tangencial',
        tipo: 'principio',
        nome: 'Redireção Tangencial',
        descricao: 'A culpa não é minha!',
        sinais: [
            'commits com mensagens como "fix do fix", "revertendo o que fulano fez"',
            'comentários culpando o ambiente, o banco de dados ou o framework',
            'código que tenta corrigir problema externo em vez de tratar a causa raiz',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'insistimento-determinante',
        tipo: 'principio',
        nome: 'Insistimento Determinante',
        descricao: 'Compila de novo que dessa vez vai dar certo.',
        sinais: [
            'histórico de commits com múltiplas tentativas para o mesmo bug: "tentativa 2", "agora vai"',
            'blocos try/catch que chamam o mesmo método novamente em loop',
            'lógica de retry sem backoff ou limite de tentativas',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'onisciencia-finita',
        tipo: 'principio',
        nome: 'Onisciência Finita',
        descricao: 'Não precisa fazer curso. Usa o que você já sabe.',
        sinais: [
            'uso de padrões obsoletos quando existem alternativas modernas no ecossistema',
            'reimplementação de utilitários que a linguagem ou framework já oferece nativamente',
            'ausência de uso de recursos como async/await, streams, ou generics disponíveis',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'imperativo-funcional',
        tipo: 'principio',
        nome: 'Imperativo Funcional',
        descricao: 'O importante é funcionar!',
        sinais: [
            'ausência de testes automatizados',
            'código comentado com "funciona, não mexa"',
            'TODO comments sem data ou responsável',
            'warnings ignorados sistematicamente',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'proatividade-egocentrica',
        tipo: 'principio',
        nome: 'Proatividade Egocêntrica',
        descricao: 'Vamos fazer do meu jeito!',
        sinais: [
            'ausência de padrões de projeto do time — cada arquivo tem convenção diferente',
            'frameworks ou bibliotecas introduzidas sem documentação da decisão',
            'configurações de ambiente hardcoded para o setup pessoal do desenvolvedor',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'devaneio-entusiasmado',
        tipo: 'principio',
        nome: 'Devaneio Entusiasmado',
        descricao: 'Lady Murphy? Balela! Faz desse jeito que nada vai dar errado.',
        sinais: [
            'ausência de tratamento de exceções ou casos de erro',
            'chamadas de API externas sem timeout ou fallback',
            'operações de I/O sem verificação de retorno',
            'código que assume que o input sempre será válido',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'foco-morcegativo',
        tipo: 'principio',
        nome: 'Foco Morcegativo',
        descricao: 'Depois eu faço isso!',
        sinais: [
            'TODO, FIXME, HACK, TEMP comments acumulados',
            'funções com nomes "temporario", "provisorio", "workaround"',
            'código comentado com "implementar depois"',
            'funções que retornam null ou lançam NotImplementedException',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'documentacao-espartana',
        tipo: 'principio',
        nome: 'Documentação Espartana',
        descricao: 'Comentários são para amadores!',
        sinais: [
            'README inexistente, vazio ou com apenas o nome do projeto',
            'funções públicas sem docstring/JSDoc/Javadoc',
            'algoritmos complexos sem nenhum comentário explicativo',
            'ausência de documentação de variáveis de ambiente necessárias',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'economia-linear',
        tipo: 'principio',
        nome: 'Economia Linear',
        descricao: 'Menos linhas é sempre melhor!',
        sinais: [
            'one-liners ilegíveis com múltiplas operações encadeadas sem variáveis intermediárias',
            'expressões ternárias aninhadas de 3+ níveis',
            'código minificado manualmente ou sem espaçamento',
            'lógica complexa colapsada em uma única instrução',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'criptocodagem',
        tipo: 'principio',
        nome: 'Criptocodagem',
        descricao: '1337 h4x0r5 dud3 lol',
        sinais: [
            'nomes de variáveis de uma letra fora de contextos matemáticos/iterativos obvios',
            'abreviações crípticas: "vlrTtlPrcFnl", "prcs_dt_usr_tmp"',
            'constantes numéricas sem nome (magic numbers)',
            'nomes em uma mistura de idiomas: português, inglês, e abreviações no mesmo arquivo',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'abstracao-ignorancial',
        tipo: 'principio',
        nome: 'Abstração Ignorancial',
        descricao: 'Esqueça o tratamento de erros. Depois cuidamos disso.',
        sinais: [
            'catch blocks vazios ou que apenas fazem console.log/print',
            'erros silenciados com pass, {}, ou comentário "ignorar"',
            'stack traces suprimidos em logs de produção',
            'ausência de validação de entrada em funções críticas',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'criatividade-diversificativa',
        tipo: 'principio',
        nome: 'Criatividade Diversificativa',
        descricao: 'Se alguém já usou uma solução, faça diferente.',
        sinais: [
            'múltiplas soluções diferentes para o mesmo tipo de problema no mesmo projeto',
            'convenções de nomenclatura inconsistentes entre módulos',
            'diferentes frameworks para a mesma função (ex: dois ORMs no mesmo projeto)',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'simplicidade-indolente',
        tipo: 'principio',
        nome: 'Simplicidade Indolente',
        descricao: 'Se tá funcionando sem isso, pra que colocar?',
        sinais: [
            'ausência de linting, formatação automática ou CI/CD',
            'dependências de segurança desatualizadas sem justificativa',
            'sem arquivo .gitignore ou com .gitignore mínimo',
            'secrets ou credenciais versionados no repositório',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'shit',
        tipo: 'principio',
        nome: 'SHIT (Sem Habilidade, Improviso Total)',
        descricao: 'Sem Habilidade, Improviso Total.',
        sinais: [
            'soluções que resolvem o problema imediato criando três problemas futuros',
            'uso de eval(), exec(), ou dynamic code execution sem justificativa',
            'regex de 200 caracteres onde uma função simples resolveria',
            'manipulação direta de strings onde existe API estruturada disponível',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
    {
        id: 'teorema-namarra',
        tipo: 'principio',
        nome: 'O Teorema de Namarra',
        descricao: 'Se você não sabe, não se preocupe, muda isso na marra que funciona.',
        sinais: [
            'commits com mensagens "não sei por que mas funcionou"',
            'valores ajustados empiricamente sem justificativa (timeouts, limites, offsets)',
            'código que muda o dado de entrada para burlar uma validação',
            'casting forçado sem verificação de tipo',
        ],
        pontos: 1,
        url: 'https://livropog.com.br/capitulos/principios',
    },
]

export const TECNICAS = [
    {
        id: 'zipomatic-versioning',
        tipo: 'tecnica',
        nome: 'Zipomatic Versioning',
        descricao: 'Controle de versão artesanal por arquivos ZIP e fé.',
        sinais: [
            'arquivos com sufixos _FINAL, _FINAL2, _AGORA_VAI, _v2, _backup no repositório',
            'pastas "antigo", "backup", "old" commitadas',
            'ausência de branches ou tags de versão',
            'arquivos .zip ou .tar versionados junto com o código',
        ],
        pontos: 2,
        url: 'https://livropog.com.br/capitulos/tecnicas/tecnica-zipomatic-versioning',
    },
    {
        id: 'incremental-patching-debug',
        tipo: 'tecnica',
        nome: 'Incremental Patching Debug',
        descricao: 'Depuração por remendo progressivo até o erro cansar.',
        sinais: [
            'histórico de commits com sequências "fix", "fix2", "fix do fix", "agora vai"',
            'uma série de pequenos patches sem descrição de causa raiz',
            'múltiplos hotfixes para o mesmo módulo em curto período',
            'código com comentários "adicionado para corrigir bug #X" sem remover o anterior',
        ],
        pontos: 2,
        url: 'https://livropog.com.br/capitulos/tecnicas/tecnica-incremental-patching-debug',
    },
    {
        id: 'my-precious',
        tipo: 'tecnica',
        nome: 'My Precious',
        descricao: 'Ownership emocional de código e centralização de contexto.',
        sinais: [
            'um único autor em >80% dos commits de um módulo crítico',
            'ausência de documentação em módulos complexity-heavy',
            'comentários com nome do autor espalhados no código (não apenas em logs de commit)',
            'PRs que só um desenvolvedor aprova',
        ],
        pontos: 2,
        url: 'https://livropog.com.br/capitulos/tecnicas/tecnica-my-precious',
    },
    {
        id: 'monkey-patching',
        tipo: 'tecnica',
        nome: 'Monkey Patching',
        descricao: 'Alteração comportamental em runtime sem mudar a origem oficial do componente.',
        sinais: [
            'sobrescrita de métodos de protótipos globais (Object.prototype, Array.prototype)',
            'monkey-patching de módulos de terceiros',
            'redefinição de comportamentos padrão da linguagem ou runtime',
            'injeção de comportamento por patch baseado em ambiente (if prod: override)',
        ],
        pontos: 2,
        url: 'https://livropog.com.br/capitulos/tecnicas/tecnica-monkey-patching',
    },
    {
        id: 'psychoding',
        tipo: 'tecnica',
        nome: 'Psychoding',
        descricao: 'Pesquisa + cópia + ajuste intuitivo + esperança.',
        sinais: [
            'mistura de padrões contraditórios que só fazem sentido juntos por acidente',
            'código que parece resolvido por tentativa e erro sem lógica coerente',
            'comentários como "não sei por que funciona mas funciona"',
            'soluções que combinam abordagens de fontes diferentes sem coesão',
        ],
        pontos: 2,
        url: 'https://livropog.com.br/capitulos/tecnicas/tecnica-psychoding',
    },
]

export const GAMBI_DESIGN_PATTERNS = [
    {
        id: 'wtf-qpe',
        tipo: 'gdp',
        nome: 'WTF / WTH / QPE (Que Porra é Essa)',
        descricao: 'Trecho inexplicável que "funciona" e ninguém tem coragem de tocar.',
        sinais: [
            'condições com dupla negação, negação de negação',
            'regex sem comentário explicativo de mais de 30 caracteres',
            'cadeias de transformações opacas sem variáveis intermediárias nomeadas',
            'lógica que só "funciona" com dados em uma ordem específica sem documentação',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-que-porra-e-essa',
    },
    {
        id: 'rcp-reuse-by-copy-paste',
        tipo: 'gdp',
        nome: 'RCP Pattern (Reuse by Copy and Paste)',
        descricao: 'Ctrl+C e Ctrl+V como framework de produtividade.',
        sinais: [
            'funções idênticas ou quase idênticas em arquivos diferentes',
            'blocos de lógica de negócio duplicados com pequenas variações',
            'constantes duplicadas com valores iguais em múltiplos arquivos',
            'ausência de abstrações compartilhadas onde seria evidente criá-las',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-reuse-by-copy-and-paste',
    },
    {
        id: 'hardcoded-data',
        tipo: 'gdp',
        nome: 'Hardcoded Data',
        descricao: 'Dados de configuração, regra de negócio e detalhes de ambiente direto no código.',
        sinais: [
            'URLs de ambiente (produção, staging) hardcoded em constantes no código',
            'IDs de banco de dados, UUIDs ou PKs fixas no código',
            'regras de negócio como "if id == 42" ou "if nome == \'Admin\'"',
            'credenciais, tokens ou senhas em código-fonte',
            'valores mágicos como timeouts de 3000ms sem variável nomeada',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-hardcoded-data',
    },
    {
        id: 'forceps',
        tipo: 'gdp',
        nome: 'Forceps',
        descricao: 'Em vez de investigar a causa raiz, o POGramador "puxa" o valor correto no ponto de uso.',
        sinais: [
            'atribuição forçada de valor correto após chamada que deveria retorná-lo',
            'correção de valor de retorno imediatamente após a chamada da função',
            'transformações de dado logo após recebê-lo para corrigir formato inesperado',
            'patches locais que compensam comportamento incorreto de módulo upstream',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-forceps',
    },
    {
        id: 'ostrich-syndrome',
        tipo: 'gdp',
        nome: 'Ostrich Syndrome Skill',
        descricao: 'Warnings, deprecações e alertas de análise estática tratados como ruído de fundo.',
        sinais: [
            '@SuppressWarnings("all"), eslint-disable, # noqa, // @ts-ignore em larga escala',
            'dependências com vulnerabilidades conhecidas sem plano de atualização',
            'TODO comments mais antigos do que 1 ano no histórico de commits',
            'linting configurado mas com centenas de warnings ignorados',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-ostrich-syndrome-skill',
    },
    {
        id: 'nonsense-flag-naming',
        tipo: 'gdp',
        nome: 'Nonsense Flag Nonsense Naming',
        descricao: 'Nomeação como criptografia artesanal: variáveis não explicam intenção.',
        sinais: [
            'variáveis com nomes: teste1, temp2, obj, data, result, val, x, y, z (fora de contexto)',
            'flags booleanas com nomes: podeTalvez, jaTrocou, flagX, status2',
            'funções com nomes como: processar(), fazer(), executar(), handle()',
            'parâmetros nomeados: p1, p2, param, arg sem docstring',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-nonsense-flag',
    },
    {
        id: 'commented-code-forever',
        tipo: 'gdp',
        nome: 'Commented Code Implementation Forever',
        descricao: 'Código morto e desativado comentado para sempre "por segurança".',
        sinais: [
            'blocos de código comentados de mais de 5 linhas',
            'imports comentados',
            'funções inteiras comentadas com "não apagar — pode precisar depois"',
            'código comentado mais antigo do que 6 meses no histórico',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-commented-code-implementation',
    },
    {
        id: 'you-shall-not-pass',
        tipo: 'gdp',
        nome: 'You Shall Not Pass',
        descricao: 'Captura total: tudo envolvido por try/catch amplo com Exception ou Throwable.',
        sinais: [
            'catch(Exception e), catch(Throwable t), except Exception as e: pass',
            'catch blocks que apenas logam e continuam sem re-throw',
            'try/catch envolvendo blocos inteiros de lógica de negócio',
            'swallowing de exceções específicas que deveriam propagar',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-you-shall-not-pass',
    },
    {
        id: 'bulletproof',
        tipo: 'gdp',
        nome: 'Perfectness Execution Bulletproof',
        descricao: 'Toda operação termina com mensagem de sucesso, independente do resultado.',
        sinais: [
            'retorno "Sucesso" ou status 200 mesmo em caso de erro interno',
            'try/catch que retorna mensagem de sucesso no catch',
            'validações que sempre passam independente do dado',
            'logs que mostram "Operação concluída" sem verificar resultado real',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-bulletproof',
    },
    {
        id: 'exception-success',
        tipo: 'gdp',
        nome: 'Exception Success',
        descricao: 'A exceção deixa de ser situação excepcional e passa a ser o fluxo normal.',
        sinais: [
            'throw usado para controle de fluxo normal (not found, validation, auth)',
            'exceções capturadas para representar resultado de negócio esperado',
            'uso de exceções como sistema de eventos ou mensageria interna',
            'catch blocks que tratam sucesso de operação',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-exception-success',
    },
    {
        id: 'string-sushiman',
        tipo: 'gdp',
        nome: 'String Sushiman',
        descricao: 'Parâmetros estruturados compactados em uma string com delimitadores mágicos.',
        sinais: [
            'strings delimitadas por "|", ";", ":", "§" usadas como estrutura de dados',
            'split() em string para extrair múltiplos campos por posição',
            'serialização manual de objetos em strings concatenadas',
            'campos estruturados trafegando como string única em API ou banco',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-string-sushiman',
    },
    {
        id: 'sleeper-human-factor',
        tipo: 'gdp',
        nome: 'Sleeper Human Factor',
        descricao: 'Aplica atraso artificial (sleep) para simular processamento ou sincronizar corridas.',
        sinais: [
            'Thread.sleep(), setTimeout(), asyncio.sleep() usados para "esperar" outro processo',
            'delays artificiais em testes para garantir que "o processo terminou"',
            'sleep usado como retry/polling sem lógica de verificação real',
            'atrasos hardcoded para sincronizar operações assíncronas',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-human-factor',
    },
    {
        id: 'black-cat-dark-room',
        tipo: 'gdp',
        nome: 'Black Cat In A Dark Room',
        descricao: 'Método que recebe um Map genérico com tudo dentro — o contrato desaparece.',
        sinais: [
            'funções que recebem Map<String,Object>, dict, object, any como parâmetro principal',
            'parâmetros do tipo HashMap/Dictionary que contêm múltiplos campos não tipados',
            'funções que fazem cast de parâmetros genéricos internamente',
            'APIs cujo contrato só é compreensível lendo a implementação completa',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-black-cat-in-a-dark-room',
    },
    {
        id: 'mega-zord',
        tipo: 'gdp',
        nome: 'Mega Zord',
        descricao: 'Superfunção: método gigante com múltiplas responsabilidades para "facilitar manutenção".',
        sinais: [
            'funções com mais de 100 linhas',
            'funções que fazem I/O, lógica de negócio e formatação de resposta no mesmo bloco',
            'métodos com mais de 5 parâmetros',
            'um único método que acessa banco, chama API, valida e retorna HTML/JSON',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-mega-zord',
    },
    {
        id: 'thunder-mega-zord',
        tipo: 'gdp',
        nome: 'THUNDER MEGA ZORD',
        descricao: 'Método gigante + contrato opaco com Map de entrada e Object[] de saída.',
        sinais: [
            'Mega Zord + Black Cat In A Dark Room no mesmo método',
            'função de 200+ linhas que recebe Map e retorna Object[] ou any',
            'método que é documentado como "faz tudo" na única linha de comentário que tem',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-thunder-mega-zord',
    },
    {
        id: 'controller-confusion',
        tipo: 'gdp',
        nome: 'Controller Confusion',
        descricao: 'O controller vira templo monolítico: valida, transforma, persiste, chama API e decide tela.',
        sinais: [
            'controllers com mais de 200 linhas',
            'lógica de negócio complexa diretamente em routes/controllers sem service layer',
            'acesso direto a banco de dados em controllers',
            'validação de regra de negócio misturada com formatação de resposta HTTP',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-controller-confusion',
    },
    {
        id: 'no-more-layers',
        tipo: 'gdp',
        nome: 'No More Layers',
        descricao: 'Arquitetura em camadas tratada como burocracia. Tudo no mesmo lugar.',
        sinais: [
            'SQL direto em arquivos de view/template',
            'lógica de negócio em arquivos de configuração',
            'routes que também são models que também são views',
            'ausência de qualquer separação de responsabilidades visível na estrutura de pastas',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-no-more-layers',
    },
    {
        id: 'db-is-our-god',
        tipo: 'gdp',
        nome: 'DB Is Our God (In DB We Trust)',
        descricao: 'O banco deixa de ser persistência e vira centro do universo: lógica, orquestração, relatório.',
        sinais: [
            'stored procedures que contêm regra de negócio complexa',
            'triggers para orquestrar fluxos de aplicação',
            'geração de HTML ou formatação de dados em queries SQL',
            'lógica de autorização implementada em views ou procedures do banco',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-db-is-our-god',
    },
    {
        id: 'snow-white-returns',
        tipo: 'gdp',
        nome: 'Snow White Returns',
        descricao: 'Múltiplos pontos de return em funções gigantes sem estratégia.',
        sinais: [
            'função com mais de 5 pontos de return',
            'return de emergência dentro de blocos condicionais aninhados',
            'funções onde é impossível seguir o fluxo de execução linearmente',
            'returns espalhados que tornam impossível aplicar guard clause simples',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-snow-white-returns',
    },
    {
        id: 'reinvented-square-wheel',
        tipo: 'gdp',
        nome: 'Reinvented Square Wheel Helper',
        descricao: 'Reimplementar manualmente algo que a linguagem, framework ou biblioteca já oferece.',
        sinais: [
            'implementação manual de debounce, throttle, memoize que existem em lodash/stdlib',
            'parser de datas escrito manualmente onde date-fns/moment/datetime resolveria',
            'implementação própria de deep clone/merge/equals',
            'utilitários de array/string reimplementados que existem nativamente',
        ],
        pontos: 3,
        url: 'https://livropog.com.br/capitulos/gambi-design-patterns/gdp-reinvented-square-wheel-helper',
    },
]

export const ALL_ITEMS = [...PRINCIPIOS, ...TECNICAS, ...GAMBI_DESIGN_PATTERNS]

export const MAX_SCORE = ALL_ITEMS.reduce((sum, item) => sum + item.pontos, 0)

/**
 * Retorna o nível de POG baseado na pontuação — escala de Mjolnir
 */
export function getNivel(score) {
    if (score <= 5)
        return {
            id: 'martelinho',
            nome: 'Martelinho de Bebê',
            emoji: '🔨',
            descricao: 'Seu código ainda não faz nem barulho.',
            tone: 'info',
        }
    if (score <= 15)
        return {
            id: 'carpinteiro',
            nome: 'Martelo de Carpinteiro',
            emoji: '🪚',
            descricao: 'Você já machuca, mas ainda não quebra nada de jeito.',
            tone: 'secondary',
        }
    if (score <= 30)
        return {
            id: 'marreta',
            nome: 'Marreta do Pedreiro',
            emoji: '⚒️',
            descricao: 'Derruba paredes. Inclusive as de separação de responsabilidade.',
            tone: 'primary',
        }
    if (score <= 45)
        return {
            id: 'mjolnir',
            nome: 'Mjolnir',
            emoji: '⚡',
            descricao: 'Somente os dignos — ou os desesperados — chegam aqui.',
            tone: 'warning',
        }
    return {
        id: 'rompe-tormentas',
        nome: 'Rompe Tormentas',
        emoji: '🪓',
        descricao: 'Você não escreve código. Você forja lendas em tempo de produção.',
        tone: 'error',
    }
}
